apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: acrworkflow1699334280414.azurecr.io/image-workflow-1699334280414:latest
          ports:
            - containerPort: 5000