apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: test-ns
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000